### PR TITLE
Added backend scaffolding and HelloWorld server

### PR DESCRIPTION
**Pull request by pramesh99**
Using express and mySQL

### CODE REVIEW

**Comment by arshmalhotra** [comment]
Why are the json files in the root directory? They don't seem to affect the iOS/frontend folders

**Comment by pramesh99** [comment]
@arshmalhotra valid

**Review by arshmalhotra — DISMISSED** [review]
LGTM

**Review by arshmalhotra — APPROVED** [review]
LGTM

**Pull request merged**
